server:
    port: 8081

eureka:
    client:
        service-url:
            defaultZone: http://localhost:8080/eureka/

spring:
    application:
        name: restaurant-listing-service
    datasource:
        url: jdbc:mysql://localhost:3306/restaurants?createDatabaseIfNotExist=true
        username: root
        password: password
        driver-class-name: com.mysql.cj.jdbc.Driver
    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true